### PR TITLE
windows ci/test: Resolve process status issues

### PR DESCRIPTION
**Pull request by mribbons**
1. Introduce SSC::Process->killed flag to prevent illegal access exception
(object was being deleted before wait thread completed)

2. Resolve exitCode -> int conversion issue:
If exitCode == 1 in previous code, (int)exitCode == 0, not good.

Note that this is basically a cross platform issue, as Win32 `GetProcessExitCode()` sets a DWORD (uint), while POSIX like `wait_pid` sets an int_32_t (currently on macos).

### CODE REVIEW

**Review by heapwolf — APPROVED** [review]
We could definitely use a test around this in the javascript apis /cc @chicoxyzzy

**Review by chicoxyzzy — COMMENTED** [review]
can we reuse the status unstead of introducing a new atomic? cc @jwerle

**Comment by mribbons** [comment]
> can we reuse the status unstead of introducing a new atomic? cc @jwerle

Great idea @chicoxyzzy 
Seems to work on windows, have force pushed to remove killed status.
Hopefully CI passes on linux/mac.

**Comment by mribbons** [comment]
@chicoxyzzy Success!

**Review by trevnorris — APPROVED** [review]

**Pull request merged**
