### PR TITLE
Release v0.5.1

### PR DESCRIPTION
**Pull request by chicoxyzzy**
# Release v0.5.1

Based on the [Socket Runtime Release Process](https://docs.google.com/document/d/105kEbRy3MrNXRQDgAV4rx0o0iMtKXS4rpJaUKTD6y7s)

## QA Tasks

- [x] `@socketsupply/socket` (darwin-x64)
- [x] `@socketsupply/socket` (darwin-arm64)
- [x] `@socketsupply/socket` (linux-x64)
- [ ] `@socketsupply/socket` (linux-arm64)
- [x] `@socketsupply/socket` (win32-x64)

### Staging
Staging releases are published to the Socket Supply GitHub NPM Package Repository at https://github.com/orgs/socketsupply/packages. Packages published there are intended for QA testing purposes only. The registry can be accessed through `npm` at https://npm.pkg.github.com/

- [x] `@socketsupply/socket` (@jwerle, @heapwolf, @chicoxyzzy)
- [x] `@socketsupply/socket-darwin-x64` (@chicoxyzzy, @bcomnes)
- [x] `@socketsupply/socket-darwin-arm64` (@jwerle, @heapwolf)
- [x] `@socketsupply/socket-linux-x64` (@jwerle)
- [ ] `@socketsupply/socket-linux-arm64` (@heapwolf)
- [x] `@socketsupply/socket-win32-x64` (@chicoxyzzy, @jwerle)

### Production
Production releases are published on the NPM Registry at https://npmjs.com/. Packages published there have gone through a testing and QA process to validate the stability, usability, and integrity of the packages.

- [x] `@socketsupply/socket` (@jwerle, @heapwolf, @chicoxyzzy)
- [x] `@socketsupply/socket-darwin-x64` (@chicoxyzzy, @bcomnes)
- [x] `@socketsupply/socket-darwin-arm64` (@jwerle, @heapwolf)
- [x] `@socketsupply/socket-linux-x64` (@jwerle)
- [ ] `@socketsupply/socket-linux-arm64` (@heapwolf)
- [x] `@socketsupply/socket-win32-x64` (@chicoxyzzy, @jwerle)

### CODE REVIEW

**Comment by lamiazar** [comment]
`@socketsupply/socket (win32-x64)` 

- [ ] ssc version
- [ ] ssc build -r
- [ ] emulator
- [ ] android
- [ ] socket app


051 version

socketapp

**Comment by lamiazar** [comment]
` @socketsupply/socket (darwin-arm64)`

- [ ] ssc version

- [ ] ssc build -r

- [ ] ios-simulator

- [ ] emulator

- [ ] android

- [ ] socket app

- [ ] ios need to be tested @chicoxyzzy 
Screenshot 2023-11-28 at 3 03 41 PM
Screenshot 2023-11-28 at 3 05 21 PM
Screenshot 2023-11-28 at 3 06 44 PM
Screenshot 2023-11-28 at 3 17 20 PM
Screenshot 2023-11-28 at 3 21 07 PM

**Comment by chicoxyzzy** [comment]
iOS checked

IMG_1861

**Comment by lamiazar** [comment]
`@socketsupply/socket (linux-x64)`

- [ ] ssc version

- [ ] ssc build -r

- [ ] emulator

- [ ] android

- [ ] create socket app
Screenshot from 2023-11-28 15-29-24
Screenshot from 2023-11-28 14-49-20
Screenshot from 2023-11-28 14-48-35

**Review by lamiazar — APPROVED** [review]

**Review by jwerle — APPROVED** [review]

**Pull request merged**
