### PR TITLE
Release v0.3.3

### PR DESCRIPTION
**Pull request by mribbons**
# Release v0.3.3

Based on the [Socket Runtime Release Process](https://docs.google.com/document/d/105kEbRy3MrNXRQDgAV4rx0o0iMtKXS4rpJaUKTD6y7s)

## QA Tasks

- [x] `@socketsupply/socket` (darwin-x64)
- [x] `@socketsupply/socket` (darwin-arm64)
- [x] `@socketsupply/socket` (linux-x64)
- [x] `@socketsupply/socket` (linux-arm64)
- [x] `@socketsupply/socket` (win32-x64)

### Staging
Staging releases are published to the Socket Supply GitHub NPM Package Repository at https://github.com/orgs/socketsupply/packages. Packages published there are intended for QA testing purposes only. The registry can be accessed through `npm` at https://npm.pkg.github.com/

- [x] `@socketsupply/socket` (@jwerle, @heapwolf, @mribbons, @chicoxyzzy)
- [x] `@socketsupply/socket-darwin-x64` (@chicoxyzzy, @mribbons)
- [x] `@socketsupply/socket-darwin-arm64` (@jwerle, @heapwolf)
- [x] `@socketsupply/socket-linux-x64` (@jwerle, @mribbons)
- [x] `@socketsupply/socket-linux-arm64` (@heapwolf)
- [x] `@socketsupply/socket-win32-x64` (@mribbons, @chicoxyzzy, @jwerle)

### Production
Production releases are published on the NPM Registry at https://npmjs.com/. Packages published there have gone through a testing and QA process to validate the stability, usability, and integrity of the packages.

- [x] `@socketsupply/socket` (@jwerle, @heapwolf, @mribbons, @chicoxyzzy)
- [x] `@socketsupply/socket-darwin-x64` (@chicoxyzzy, @mribbons)
- [x] `@socketsupply/socket-darwin-arm64` (@jwerle, @heapwolf)
- [x] `@socketsupply/socket-linux-x64` (@jwerle, @mribbons)
- [x] `@socketsupply/socket-linux-arm64` (@heapwolf)
- [x] `@socketsupply/socket-win32-x64` (@mribbons, @chicoxyzzy, @jwerle)

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
I think it's better to squash commits so we can tag the `release-v0.3.3` commit with `v0.3.3` tag

**Comment by lamiazar** [comment]
`@socketsupply/socket (win32-x64)`

- [ ] ssc build -r -o
- [ ] ssc build -r --platform=android-emulator
- [ ] ssc build -r --platform=android

**Comment by lamiazar** [comment]
`@socketsupply/socket (darwin-x64)`
- [x] ssc build -r
- [x] ssc build -r --platform=ios-simulator
- [x] ssc build -r --platform=android
- [x] ssc build -r --platform=android-emulator
- [ ] ssc build -r --platform=iOS - I didn't test this, because my device is not set up yet

**Comment by lamiazar** [comment]
I'll approve `linux-x64` once the android app is tested.

**Comment by lamiazar** [comment]
`TODO`

- [ ] test `ios application` on `darwin-x64` 
cc @chicoxyzzy

**Comment by lamiazar** [comment]
We had a workaround to test `android application` on `linux-x64` (installed on hyper-v), I followed @mribbons's instructions:
-I located the `.apk` file (`find . -name "*-dev-debug.apk"`)
-I copied the file to my phone(used google drive)
Screenshot_20230607_184414_My Files
-Then I installed the app downloaded to my phone
Screenshot_20230607_173530

**Comment by heapwolf** [comment]
+ @socketsupply/socket-linux-arm64@0.3.3

**Comment by heapwolf** [comment]
✅ @socketsupply/socket-darwin-arm64@0.3.3

**Comment by chicoxyzzy** [comment]
published top-level one

**Review by chicoxyzzy — APPROVED** [review]

**Comment by chicoxyzzy** [comment]
now we only need to rebase the branches

CI failure fix is in https://github.com/socketsupply/socket/pull/487

**Review by jwerle — APPROVED** [review]

**Pull request merged**
