### PR TITLE
Release v0.5.0

### PR DESCRIPTION
**Pull request by chicoxyzzy**
# Release v0.5.0

Based on the [Socket Runtime Release Process](https://docs.google.com/document/d/105kEbRy3MrNXRQDgAV4rx0o0iMtKXS4rpJaUKTD6y7s)

## QA Tasks

- [x] `@socketsupply/socket` (darwin-x64)
- [x] `@socketsupply/socket` (darwin-arm64)
- [x] `@socketsupply/socket` (linux-x64)
- [ ] `@socketsupply/socket` (linux-arm64)
- [x] `@socketsupply/socket` (win32-x64)

### Staging
Staging releases are published to the Socket Supply GitHub NPM Package Repository at https://github.com/orgs/socketsupply/packages. Packages published there are intended for QA testing purposes only. The registry can be accessed through `npm` at https://npm.pkg.github.com/

- [x] `@socketsupply/socket` (@jwerle, @heapwolf, @chicoxyzzy)
- [x] `@socketsupply/socket-darwin-x64` (@chicoxyzzy, @bcomnes)
- [x] `@socketsupply/socket-darwin-arm64` (@jwerle, @heapwolf)
- [x] `@socketsupply/socket-linux-x64` (@jwerle)
- [ ] `@socketsupply/socket-linux-arm64` (@heapwolf)
- [x] `@socketsupply/socket-win32-x64` (@chicoxyzzy, @jwerle)

### Production
Production releases are published on the NPM Registry at https://npmjs.com/. Packages published there have gone through a testing and QA process to validate the stability, usability, and integrity of the packages.

- [x] `@socketsupply/socket` (@jwerle, @heapwolf, @chicoxyzzy)
- [x] `@socketsupply/socket-darwin-x64` (@chicoxyzzy, @bcomnes)
- [x] `@socketsupply/socket-darwin-arm64` (@jwerle, @heapwolf)
- [x] `@socketsupply/socket-linux-x64` (@jwerle)
- [ ] `@socketsupply/socket-linux-arm64` (@heapwolf)
- [x] `@socketsupply/socket-win32-x64` (@chicoxyzzy, @jwerle)

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Tested the `socket-darwin-x64` version. All the Apple builds work:
- [x] mac
- [x] ios simulator
- [x] ios
- [ ] android emulator
- [ ] android

Android Emulator is failing with
```
➜ ssc build -r --platform=android-emulator
• cleaned: /Users/chicoxyzzy/dev/other/test-s/build/android-emulator +55ms
• package prepared +2548ms
[=======================================] 100% Computing updates...

• /Users/chicoxyzzy/Library/Android/sdk/ndk/26.0.10792818/ndk-build -j NDK_PROJECT_PATH="/Users/chicoxyzzy/dev/other/test-s/build/android-emulator/app/src/main" NDK_APPLICATION_MK="/Users/chicoxyzzy/dev/other/test-s/build/android-emulator/app/src/main/jni/Application.mk" NDK_DEBUG=1 APP_PLATFORM=android-34 NDK_LIBS_OUT="/Users/chicoxyzzy/dev/other/test-s/build/android-emulator/app/src/main/jniLibs" >/dev/null 2>&1 +5506ms
• ERROR: ndk build failed. +0ms
```

I don't have Android device to check it

**Comment by chicoxyzzy** [comment]
ugh, TS definitions are outdated

**Comment by chicoxyzzy** [comment]
Android issues https://github.com/socketsupply/socket/issues/793

**Comment by lamiazar** [comment]
@socketsupply/socket (darwin-arm64)

- [ ] ssc version 

Screenshot 2023-11-22 at 1 07 57 PM

- [ ] ssc build -r

Screenshot 2023-11-22 at 1 09 08 PM

- [ ] ssc build -r --platform=ios-simulator

Screenshot 2023-11-22 at 1 10 12 PM

- X ssc build -r --platform=android
```
ssc build -r --platform=android
• package prepared +3768ms
[=======================================] 100% Computing updates...             

• /Users/lamia/Library/Android/sdk/ndk/26.0.10792818/ndk-build -j NDK_PROJECT_PATH="/Users/lamia/test-socket-application/build/android/app/src/main" NDK_APPLICATION_MK="/Users/lamia/test-socket-application/build/android/app/src/main/jni/Application.mk" NDK_DEBUG=1 APP_PLATFORM=android-34 NDK_LIBS_OUT="/Users/lamia/test-socket-application/build/android/app/src/main/jniLibs" >/dev/null 2>&1 +4770ms
• ERROR: ndk build failed. +0ms
lamia@lamias-Air test-socket-application % ssc build -r --platform=android
• cleaned: /Users/lamia/test-socket-application/build/android/app/src +22ms
• package prepared +17155ms
[=======================================] 100% Computing updates...             

• /Users/lamia/Library/Android/sdk/ndk/26.0.10792818/ndk-build -j NDK_PROJECT_PATH="/Users/lamia/test-socket-application/build/android/app/src/main" NDK_APPLICATION_MK="/Users/lamia/test-socket-application/build/android/app/src/main/jni/Application.mk" NDK_DEBUG=1 APP_PLATFORM=android-34 NDK_LIBS_OUT="/Users/lamia/test-socket-application/build/android/app/src/main/jniLibs" >/dev/null 2>&1 +2363ms
• ERROR: ndk build failed. +0ms

```

-X ssc build -r --platform=android-emulator
```
lamia@lamias-Air test-socket-application % ssc build -r --platform=android-emulator

• cleaned: /Users/lamia/test-socket-application/build/android-emulator +42ms
• package prepared +1331ms
[=======================================] 100% Computing updates...             

• /Users/lamia/Library/Android/sdk/ndk/26.0.10792818/ndk-build -j NDK_PROJECT_PATH="/Users/lamia/test-socket-application/build/android-emulator/app/src/main" NDK_APPLICATION_MK="/Users/lamia/test-socket-application/build/android-emulator/app/src/main/jni/Application.mk" NDK_DEBUG=1 APP_PLATFORM=android-34 NDK_LIBS_OUT="/Users/lamia/test-socket-application/build/android-emulator/app/src/main/jniLibs" >/dev/null 2>&1 +2569ms
• ERROR: ndk build failed. +0ms
```

**Comment by lamiazar** [comment]
For Android on both: `windows` and `darwin-arm64`, the app is installed but it doesn't open, I see it try to open on my Mac and then it closes immediately with this msg:
Screenshot_20231122_153450_One UI Home

**Comment by lamiazar** [comment]
@socketsupply/socket (linux-x64)
 

- [ ] ssc version



-  ssc build -r



-emulator
Screenshot from 2023-11-22 16-17-54

**Review by lamiazar — APPROVED** [review]

**Review by bcomnes — APPROVED** [review]

**Review by jwerle — APPROVED** [review]

**Pull request merged**
