### PR TITLE
Implement 'resolveURLPathForWebView()' function

### PR DESCRIPTION
**Pull request by bcomnes**
Introduces `IPC::Router::resolveURLPathForWebView` which unifies redirect and resolution logic for finding html pages similar to how nginx and other standard static files do it. 

Closes https://github.com/socketsupply/socket/issues/649

## Spec

It implements this logic:

```tree 
.
    ├── a-conflict-index
    │             └── index.html
    ├── a-conflict-index.html
    ├── an-index-file
    │            ├── a-html-file.html
    │            └── index.html
    ├── another-file.html
    └── index.html

    Subtleties:
    Direct file navigation always wins
    /foo/index.html have precedent over foo.html
    /foo redirects to /foo/ when there is a /foo/index.html
    
    '/' -> '/index.html'
    '/index.html' -> '/index.html'
    '/a-conflict-index' -> redirect to '/a-conflict-index/'
    '/another-file' -> '/another-file.html'
    '/another-file.html' -> '/another-file.html'
    '/an-index-file/' -> '/an-index-file/index.html'
    '/an-index-file' -> redirect to '/an-index-file/'
    '/an-index-file/a-html-file' -> '/an-index-file/a-html-file.html'
```

## Platform Support

- [x] Android
- [x] iOS
- [x] Linux
- [x] macOS
- [x] Windows

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Maybe we can add this package to https://github.com/socketsupply/socket/tree/master/npm/packages/%40socketsupply?

**Comment by bcomnes** [comment]
Just working on getting the resolution algorithm right and will then get it integrated into the rest of the project correctly.

**Comment by bcomnes** [comment]
When this is ready, let's delete the html-redirects folder, but port some of the tests out of it.

**Comment by bcomnes** [comment]
Ok, I removed the JS implementation in favor of the C++ version, and ported the js tests to a comment explaining how it should work.

**Comment by chicoxyzzy** [comment]
can we add tests for this?

**Comment by jwerle** [comment]
> can we add tests for this?

we will in a subsequent refactor + PR

**Comment by jwerle** [comment]
we need testing infrastructure for c++ 🙃

**Comment by chicoxyzzy** [comment]
> we need testing infrastructure for c++ 🙃

I meant e2e tests

**Review by chicoxyzzy — APPROVED** [review]

**Comment by jwerle** [comment]
> > we need testing infrastructure for c++ 🙃
> 
> I meant e2e tests

@bcomnes we can set this up today

**Comment by bcomnes** [comment]
We got android done today, but not quite end to end tests. Will work on that tomorrow.

**Comment by jwerle** [comment]
We have a small Windows error to fix next

**Comment by bcomnes** [comment]
I'll finish up the integration tests.

**Review by jwerle — APPROVED** [review]

**Comment by bcomnes** [comment]
Ok, confirmed that this is working with expected behavior.

**Pull request merged**
