### PR TITLE
install.ps1: resolve issues

### PR DESCRIPTION
**Pull request by mribbons**
Get-Command wasn't detecting absense of commands
libuv requires nmake on windows, install vs_build tools to get it Don't use LLVM/Clang

### CODE REVIEW

**Comment by heapwolf** [comment]
Did you try running this in a non-vs-tools command-prompt?

**Comment by mribbons** [comment]
@heapwolf Yes, fully tested from a fresh windows install, both powershell and cmd.

**Comment by heapwolf** [comment]
@trevnorris or @jwerle can you test this on windows? I still don't have a windows machine available :(

**Comment by mribbons** [comment]
I need to do some refactoring on this one to reintroduce correct use of ``$LIBUV_BUILD_TYPE``, hold off on testing or merging.

**Comment by mribbons** [comment]
Superseded by #166

**Pull request closed without merging**
