### PR TITLE
fix(types): extend Window type with built-in events

### PR DESCRIPTION
**Pull request by aleclarson**

### CODE REVIEW

**Review by chicoxyzzy — COMMENTED** [review]
were those added with `npm run gen` or manually?

**Comment by aleclarson** [comment]
Ah good point!

**Comment by chicoxyzzy** [comment]
Yeah, we generate type defs with `npm run gen`, so manually added stuff will be overwritten

**Comment by aleclarson** [comment]
I don't think it's an issue. I'm seeing the types in the `build/npm` package, no problem.

**Review by jwerle — APPROVED** [review]

**Pull request merged**
