### PR TITLE
Release v0.5.3

### PR DESCRIPTION
**Pull request by chicoxyzzy**
# Release v0.5.3

Based on the [Socket Runtime Release Process](https://docs.google.com/document/d/105kEbRy3MrNXRQDgAV4rx0o0iMtKXS4rpJaUKTD6y7s)

## QA Tasks

- [x] `@socketsupply/socket` (darwin-x64)
- [x] `@socketsupply/socket` (darwin-arm64)
- [x] `@socketsupply/socket` (linux-x64)
- [x] `@socketsupply/socket` (linux-arm64)
- [x] `@socketsupply/socket` (win32-x64)

### Staging
Staging releases are published to the Socket Supply GitHub NPM Package Repository at https://github.com/orgs/socketsupply/packages. Packages published there are intended for QA testing purposes only. The registry can be accessed through `npm` at https://npm.pkg.github.com/

- [x] `@socketsupply/socket` (@jwerle, @heapwolf, @chicoxyzzy)
- [x] `@socketsupply/socket-darwin-x64` (@chicoxyzzy, @bcomnes)
- [x] `@socketsupply/socket-darwin-arm64` (@jwerle, @heapwolf)
- [x] `@socketsupply/socket-linux-x64` (@jwerle)
- [x] `@socketsupply/socket-linux-arm64` (@heapwolf)
- [x] `@socketsupply/socket-win32-x64` (@chicoxyzzy, @jwerle)

### Production
Production releases are published on the NPM Registry at https://npmjs.com/. Packages published there have gone through a testing and QA process to validate the stability, usability, and integrity of the packages.

- [x] `@socketsupply/socket` (@jwerle, @heapwolf, @chicoxyzzy)
- [x] `@socketsupply/socket-darwin-x64` (@chicoxyzzy, @bcomnes)
- [x] `@socketsupply/socket-darwin-arm64` (@jwerle, @heapwolf)
- [x] `@socketsupply/socket-linux-x64` (@jwerle)
- [ ] `@socketsupply/socket-linux-arm64` (@heapwolf)
- [x] `@socketsupply/socket-win32-x64` (@chicoxyzzy, @jwerle)

### CODE REVIEW

**Comment by lamiazar** [comment]
` @socketsupply/socket (linux-arm64)`

- [ ] ssc version
Screenshot from 2023-12-07 13-14-23

- [ ] Desktop app( I still have the issue with dispaly but @jwerle askd to move on because it's probably an issue with my system)

- [ ] create socket app

**Comment by chicoxyzzy** [comment]
darwin-amd64 QA:
- [ ] - macOS
- [ ] - iOS Simulator
- [ ] - iOS
- [ ] - Android Emulator

**Comment by lamiazar** [comment]
`@socketsupply/socket (linux-x64)`

- [ ] ssc version
Screenshot from 2023-12-07 13-47-10

- [ ] desktop app
Screenshot from 2023-12-07 13-48-40

**Comment by lamiazar** [comment]
`@socketsupply/socket (darwin-arm64)`

- [ ] ssc version

- [ ] Desktop app+ CPU check

- [ ] android

- [ ] android emulator

- [ ] ios simulator

- [ ] create socket app

- [ ] simulator need to be tested cc @chicoxyzzy 

Screenshot 2023-12-07 at 2 38 12 PM
Screenshot 2023-12-07 at 2 53 40 PM
Screenshot 2023-12-07 at 2 56 15 PM
Screenshot 2023-12-07 at 2 32 32 PM
Screenshot 2023-12-07 at 2 35 57 PM

**Review by lamiazar — APPROVED** [review]

**Review by jwerle — APPROVED** [review]

**Pull request merged**
