### PR TITLE
Release v0.4.0

### PR DESCRIPTION
**Pull request by jwerle**
# Release v0.4.0

Based on the [Socket Runtime Release Process](https://docs.google.com/document/d/105kEbRy3MrNXRQDgAV4rx0o0iMtKXS4rpJaUKTD6y7s)

## QA Tasks

- [x] `@socketsupply/socket` (darwin-x64)
- [x] `@socketsupply/socket` (darwin-arm64)
- [x] `@socketsupply/socket` (linux-x64)
- [x] `@socketsupply/socket` (linux-arm64)
- [x] `@socketsupply/socket` (win32-x64)

### Staging
Staging releases are published to the Socket Supply GitHub NPM Package Repository at https://github.com/orgs/socketsupply/packages. Packages published there are intended for QA testing purposes only. The registry can be accessed through `npm` at https://npm.pkg.github.com/

- [x] `@socketsupply/socket` (@jwerle, @heapwolf, @chicoxyzzy)
- [x] `@socketsupply/socket-darwin-x64` (@chicoxyzzy, @bcomnes)
- [x] `@socketsupply/socket-darwin-arm64` (@jwerle, @heapwolf)
- [x] `@socketsupply/socket-linux-x64` (@jwerle)
- [x] `@socketsupply/socket-linux-arm64` (@heapwolf)
- [x] `@socketsupply/socket-win32-x64` (@chicoxyzzy, @jwerle)

### Production
Production releases are published on the NPM Registry at https://npmjs.com/. Packages published there have gone through a testing and QA process to validate the stability, usability, and integrity of the packages.

- [x] `@socketsupply/socket` (@jwerle, @heapwolf, @chicoxyzzy)
- [x] `@socketsupply/socket-darwin-x64` (@chicoxyzzy, @bcomnes)
- [x] `@socketsupply/socket-darwin-arm64` (@jwerle, @heapwolf)
- [x] `@socketsupply/socket-linux-x64` (@jwerle)
- [x] `@socketsupply/socket-linux-arm64` (@heapwolf)
- [x] `@socketsupply/socket-win32-x64` (@chicoxyzzy, @jwerle)

### CODE REVIEW

**Comment by lamiazar** [comment]
`@socketsupply/socket-darwin-x64`✔️

- [ ] `ssc --version`
ssc-v
- [ ] `desktop application`
sscbuildr
- [ ] `iOS simulator application`
sscsimu
- [ ] ` iOS application `
- [ ] `Android application`
IMG_1133
- [ ] `Android emulator application`
emulator

**Comment by lamiazar** [comment]
`@socketsupply/socket (linux-x64)` ✔️

- [ ] `ssc version`

Screenshot from 2023-09-08 11-26-05

- [ ] `Desktop app`

Screenshot from 2023-09-08 11-28-43

- [ ] `Android emulator application`

Screenshot from 2023-09-08 11-44-16

- [ ] `Android App`
I followed those steps:(I'm using a Vm)
1-Find the .apk file by running this command:
  find . -name “*-dev-debug.apk”
2- copy .apk to your phone.
3- install the file.
9. Verify Android emulator application (if applicable)

Screenshot_20230908_121808


Screenshot_20230908_121419_My Files

**Review by lamiazar — APPROVED** [review]

**Comment by chicoxyzzy** [comment]
@lamiazar this is `amd64` build, not `arm64`. You need computer with arm CPU or arm virtual machine to test `linux-arm64`

**Comment by lamiazar** [comment]
> @lamiazar this is amd64 build, not arm64. You need computer with arm CPU or arm virtual machine to test linux-arm64

Screenshot from 2023-09-11 14-12-39

**Comment by chicoxyzzy** [comment]
That was an incorrect deb package name on a screenshot. #568 

not a blocker

**Pull request merged**
