### PR TITLE
Fix `ssc run` to be on par with `ssc build`

### PR DESCRIPTION
**Pull request by chicoxyzzy**
Next step is to make things DRY for `build` and `run`. Probably we can just call `run` from `build` filtering and passing arguments

### CODE REVIEW

**Review by mribbons — APPROVED** [review]

**Comment by chicoxyzzy** [comment]
I just found a few more issue with `run` :(
So I'm going to separate `build -r` / `run` to a separate step in this PR to avoid further divergence

**Comment by chicoxyzzy** [comment]
@mribbons @jwerle I can't make it work after rebase. I've tried a few times from scratch, but my knowledge is not enough. Can you halp me to move all the run stuff from in the `ssc build` inside of the latest `if (flagShouldRun) {` body so we have only one such condition there?

**Comment by chicoxyzzy** [comment]
Otherwise I can't share that code between `ssc build` and `ssc run` later

**Comment by chicoxyzzy** [comment]
replaced by #409 

Further changes will be in upcoming PRs

**Pull request closed without merging**
