### PR TITLE
Release v0.5.2

### PR DESCRIPTION
**Pull request by chicoxyzzy**
# Release v0.5.2

Based on the [Socket Runtime Release Process](https://docs.google.com/document/d/105kEbRy3MrNXRQDgAV4rx0o0iMtKXS4rpJaUKTD6y7s)

## QA Tasks

- [x] `@socketsupply/socket` (darwin-x64)
- [x] `@socketsupply/socket` (darwin-arm64)
- [x] `@socketsupply/socket` (linux-x64)
- [x] `@socketsupply/socket` (linux-arm64)
- [x] `@socketsupply/socket` (win32-x64)

### Staging
Staging releases are published to the Socket Supply GitHub NPM Package Repository at https://github.com/orgs/socketsupply/packages. Packages published there are intended for QA testing purposes only. The registry can be accessed through `npm` at https://npm.pkg.github.com/

- [x] `@socketsupply/socket` (@jwerle, @heapwolf, @chicoxyzzy)
- [x] `@socketsupply/socket-darwin-x64` (@chicoxyzzy, @bcomnes)
- [x] `@socketsupply/socket-darwin-arm64` (@jwerle, @heapwolf)
- [x] `@socketsupply/socket-linux-x64` (@jwerle)
- [x] `@socketsupply/socket-linux-arm64` (@heapwolf)
- [x] `@socketsupply/socket-win32-x64` (@chicoxyzzy, @jwerle)

### Production
Production releases are published on the NPM Registry at https://npmjs.com/. Packages published there have gone through a testing and QA process to validate the stability, usability, and integrity of the packages.

- [x] `@socketsupply/socket` (@jwerle, @heapwolf, @chicoxyzzy)
- [x] `@socketsupply/socket-darwin-x64` (@chicoxyzzy, @bcomnes)
- [x] `@socketsupply/socket-darwin-arm64` (@jwerle, @heapwolf)
- [x] `@socketsupply/socket-linux-x64` (@jwerle)
- [x] `@socketsupply/socket-linux-arm64` (@heapwolf)
- [x] `@socketsupply/socket-win32-x64` (@chicoxyzzy, @jwerle)

### CODE REVIEW

**Comment by lamiazar** [comment]
`@socketsupply/socket (linux-arm64)`

- [ ] ssc version

Screenshot from 2023-12-05 12-09-04


- [ ] Desktop app is opening but the appearance is weird cc @jwerle 

Screenshot from 2023-12-05 12-10-10

**Comment by lamiazar** [comment]
` @socketsupply/socket (win32-x64)`

- [ ] ssc version

v52

- [ ] Desktop app

-r52

- [ ] emulator


- [ ] android


- [ ] create socket app
socket-app

**Comment by lamiazar** [comment]
`@socketsupply/socket (darwin-arm64)`

- [ ] ssc version


Screenshot 2023-12-05 at 12 57 16 PM


- [ ] Desktop app + CPU check


Screenshot 2023-12-05 at 1 00 11 PM
Screenshot 2023-12-05 at 12 59 53 PM


- [ ] simulator

Screenshot 2023-12-05 at 1 01 22 PM

- [ ] emulator
Screenshot 2023-12-05 at 1 05 27 PM


- [ ] socket app

**Comment by chicoxyzzy** [comment]
both simulator and ios app work for me

**Comment by lamiazar** [comment]
` @socketsupply/socket (linux-x64)`

- [ ] ssc version
Screenshot from 2023-12-05 13-43-45

- [ ] desktop app
Screenshot from 2023-12-05 13-44-40

- [ ] android +emulator

- [ ] create socket app
Screenshot from 2023-12-05 14-09-25

**Pull request merged**
