### PR TITLE
Release v0.3.2

### PR DESCRIPTION
**Pull request by mribbons**
# Release v0.3.2

Based on the [Socket Runtime Release Process](https://docs.google.com/document/d/105kEbRy3MrNXRQDgAV4rx0o0iMtKXS4rpJaUKTD6y7s)

## QA Tasks

- [x] `@socketsupply/socket` (darwin-x64)
- [x] `@socketsupply/socket` (darwin-arm64)
- [x] `@socketsupply/socket` (linux-x64)
- [x] `@socketsupply/socket` (linux-arm64)
- [x] `@socketsupply/socket` (win32-x64)

### Staging
Staging releases are published to the Socket Supply GitHub NPM Package Repository at https://github.com/orgs/socketsupply/packages. Packages published there are intended for QA testing purposes only. The registry can be accessed through `npm` at https://npm.pkg.github.com/

- [x] `@socketsupply/socket` (@jwerle, @heapwolf, @mribbons, @chicoxyzzy)
- [x] `@socketsupply/socket-darwin-x64` (@chicoxyzzy, @mribbons)
- [x] `@socketsupply/socket-darwin-arm64` (@jwerle, @heapwolf)
- [x] `@socketsupply/socket-linux-x64` (@jwerle, @mribbons)
- [x] `@socketsupply/socket-linux-arm64` (@heapwolf)
- [x] `@socketsupply/socket-win32-x64` (@mribbons, @chicoxyzzy, @jwerle)

### Production
Production releases are published on the NPM Registry at https://npmjs.com/. Packages published there have gone through a testing and QA process to validate the stability, usability, and integrity of the packages.

- [x] `@socketsupply/socket` (@jwerle, @heapwolf, @mribbons, @chicoxyzzy)
- [x] `@socketsupply/socket-darwin-x64` (@chicoxyzzy, @mribbons)
- [x] `@socketsupply/socket-darwin-arm64` (@jwerle, @heapwolf)
- [x] `@socketsupply/socket-linux-x64` (@jwerle, @mribbons)
- [x] `@socketsupply/socket-linux-arm64` (@heapwolf)
- [x] `@socketsupply/socket-win32-x64` (@mribbons, @chicoxyzzy, @jwerle)

### CODE REVIEW

**Comment by lamiazar** [comment]
For `@socketsupply/socket (win32-x64)` I was able to install the new version but the app doesn't open when I run `ssc build -r`
ssc build -r

I opened a new window and I run it again and it was the same thing 
Capture


Same for the emulator `ssc build -r --platform=android-emulator`
emue

**Comment by lamiazar** [comment]
I just finished setting up` Linux arm 64` on my mac machine also tested the new release -->`Approved`
Screenshot from 2023-05-30 12-56-56

**Comment by chicoxyzzy** [comment]
I think we need cherry pick https://github.com/socketsupply/socket/pull/472 into 0.3.2
WDYT? @mribbons @jwerle

**Comment by chicoxyzzy** [comment]
this will require commits reordering

**Review by lamiazar — APPROVED** [review]

**Review by chicoxyzzy — APPROVED** [review]

**Comment by lamiazar** [comment]
@mribbons I double checked `android` on `linux-x64` and I'm getting an error:
```
 ssc build -r -o --platform=android
sh: 1: ifconfig: not found
• package prepared +9751ms
[=======================================] 100% Computing updates...             

Starting a Gradle Daemon, 2 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :app
WARNING:The option setting 'android.experimental.legacyTransform.forceNonIncremental=true' is experimental.
The current default is 'false'.

> Task :app:compileDevDebugKotlin
w: /home/mia/test-socket-application/build/android/app/src/main/java/com/beepboop/window.kt: (31, 9): Variable 'runtime' is never used
w: /home/mia/test-socket-application/build/android/app/src/main/java/com/beepboop/window.kt: (34, 82): Parameter 'result' is never used, could be renamed to _
w: /home/mia/test-socket-application/build/android/app/src/main/java/com/beepboop/window.kt: (44, 20): 'setter for allowFileAccessFromFileURLs: Boolean' is deprecated. Deprecated in Java

> Task :app:compileLiveDebugKotlin
w: /home/mia/test-socket-application/build/android/app/src/main/java/com/beepboop/window.kt: (31, 9): Variable 'runtime' is never used
w: /home/mia/test-socket-application/build/android/app/src/main/java/com/beepboop/window.kt: (34, 82): Parameter 'result' is never used, could be renamed to _
w: /home/mia/test-socket-application/build/android/app/src/main/java/com/beepboop/window.kt: (44, 20): 'setter for allowFileAccessFromFileURLs: Boolean' is deprecated. Deprecated in Java

BUILD SUCCESSFUL in 43s
70 actionable tasks: 70 executed

> Configure project :app
WARNING:The option setting 'android.experimental.legacyTransform.forceNonIncremental=true' is experimental.
The current default is 'false'.

> Task :app:compileDevReleaseKotlin
w: /home/mia/test-socket-application/build/android/app/src/main/java/com/beepboop/window.kt: (31, 9): Variable 'runtime' is never used
w: /home/mia/test-socket-application/build/android/app/src/main/java/com/beepboop/window.kt: (34, 82): Parameter 'result' is never used, could be renamed to _
w: /home/mia/test-socket-application/build/android/app/src/main/java/com/beepboop/window.kt: (44, 20): 'setter for allowFileAccessFromFileURLs: Boolean' is deprecated. Deprecated in Java

> Task :app:compileLiveReleaseKotlin
w: /home/mia/test-socket-application/build/android/app/src/main/java/com/beepboop/window.kt: (31, 9): Variable 'runtime' is never used
w: /home/mia/test-socket-application/build/android/app/src/main/java/com/beepboop/window.kt: (34, 82): Parameter 'result' is never used, could be renamed to _
w: /home/mia/test-socket-application/build/android/app/src/main/java/com/beepboop/window.kt: (44, 20): 'setter for allowFileAccessFromFileURLs: Boolean' is deprecated. Deprecated in Java

BUILD SUCCESSFUL in 42s
140 actionable tasks: 86 executed, 54 up-to-date
• Installing app... +99472ms
• Wait for ADB Install timed out. +123601ms
• ERROR: failed to install APK to Android Emulator (adb) +0ms
```

**Comment by mribbons** [comment]
> Wait for ADB Install timed out. +123601ms

@lamiazar My guess is that the VM is just a bit too slow. Let's try increasing the timeout. 
```bash
VERBOSE=1 SSC_ANDROID_TIMEOUT=300000 ssc build -r -o --platform=android
```
This should wait 5 minutes for the emulator to boot before failing.

**Pull request merged**
